### ISSUE TITLE
Fatal Error: Concurrent Map Writes

### ISSUE THREAD

**Issue by frankgreco** [northwesternmutual/kanali#12]
```go
August 3rd 2017, 19:28:27.000 fatal error: concurrent map read and map write   - 
August 3rd 2017, 19:28:27.000    - 
August 3rd 2017, 19:28:27.000 goroutine 10438 [running]:   - 
August 3rd 2017, 19:28:27.000 runtime.throw(0x2177f86, 0x21)   - 
August 3rd 2017, 19:28:27.000   /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc421833960 sp=0xc421833940   - 
August 3rd 2017, 19:28:27.000 runtime.mapaccess2_faststr(0x1fa0e00, 0xc420fba7e0, 0x2159ed0, 0x9, 0xc420fba7e0, 0xe7c5b0)  - 
August 3rd 2017, 19:28:27.000   /usr/local/go/src/runtime/hashmap_fast.go:326 +0x50a fp=0xc4218339c0 sp=0xc421833960   - 
August 3rd 2017, 19:28:27.000 github.com/northwesternmutual/kanali/monitor.GetCtxMetric(0x2d3b6a0, 0xc420fba840, 0x2159ed0, 0x9, 0x7, 0xa)  - 
August 3rd 2017, 19:28:27.000 github.com/northwesternmutual/kanali/cmd.glob..func1(0x2d1db40, 0xc42037a900, 0x0, 0x12)  - 
August 3rd 2017, 19:28:27.000   /go/src/github.com/northwesternmutual/kanali/monitor/metrics.go:58 +0xc4 fp=0xc421833a10 sp=0xc4218339c0  - 
August 3rd 2017, 19:28:27.000 github.com/northwesternmutual/kanali/monitor.getFields(0x2d3b6a0, 0xc420fba840, 0xc42147c480)   - 
August 3rd 2017, 19:28:27.000   /go/src/github.com/northwesternmutual/kanali/monitor/influxdb.go:110 +0x62 fp=0xc421833ab0 sp=0xc421833a10  - 
August 3rd 2017, 19:28:27.000 github.com/northwesternmutual/kanali/monitor.(*InfluxController).WriteRequestData(0x0, 0x2d3b6a0, 0xc420fba840, 0x0, 0x0)   - 
August 3rd 2017, 19:28:27.000   /go/src/github.com/northwesternmutual/kanali/monitor/influxdb.go:80 +0x1b6 fp=0xc421833bd8 sp=0xc421833ab0  - 
August 3rd 2017, 19:28:27.000 github.com/northwesternmutual/kanali/handlers.Logger.func1(0x2d3a2a0, 0xc420a39260, 0xc42041ce00)   - 
August 3rd 2017, 19:28:27.000   /go/src/github.com/northwesternmutual/kanali/handlers/logger.go:59 +0x8b6 fp=0xc421833ce8 sp=0xc421833bd8   - 
August 3rd 2017, 19:28:27.000 net/http.HandlerFunc.ServeHTTP(0xc420421ee0, 0x2d3a2a0, 0xc420a39260, 0xc42041ce00)  - 
August 3rd 2017, 19:28:27.000   /usr/local/go/src/net/http/server.go:1942 +0x44 fp=0xc421833d10 sp=0xc421833ce8  - 
August 3rd 2017, 19:28:27.000 net/http.serverHandler.ServeHTTP(0xc420440160, 0x2d3a2a0, 0xc420a39260, 0xc42041ce00)  - 
August 3rd 2017, 19:28:27.000   /usr/local/go/src/net/http/server.go:2568 +0x92 fp=0xc421833d58 sp=0xc421833d10  - 
August 3rd 2017, 19:28:27.000 net/http.(*conn).serve(0xc420cf4000, 0x2d3b5e0, 0xc420308240)  - 
August 3rd 2017, 19:28:27.000   /usr/local/go/src/net/http/server.go:1825 +0x612 fp=0xc421833fc8 sp=0xc421833d58   - 
August 3rd 2017, 19:28:27.000 runtime.goexit()
```

**Comment by frankgreco** [comment]
@kh34
